# Site settings

# Setup
title:      bwvoss.github.io
tagline:    'Helping Engineers Think more like PMs and PMs Think more like Engineers'
description: 'Personal thoughts about software engineering and technical product management'
url:         https://bwvoss.github.io
baseurl:     ''
paginate:    5
permalink:   pretty

# About/contact
author:
  name: Ben Voss
  url:  ''
  email: bwvoss@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
google_analytics_id: G-9P5GETRZRN
