# Site settings

# Setup
title:      Personal Site
tagline:    'A Jekyll theme'
description: 'A description'
url:         https://bwvoss.github.io
baseurl:     ''
paginate:    5
permalink:   pretty

# About/contact
author:
  name: Ben Voss
  url:  ''
  email: bwvoss@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
# google_analytics_id: UA-146052-15

