# Site settings
email: bwvoss@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://bwvoss.github.io" # the base hostname & protocol for your site

author:
  name: Ben Voss
  url:  ""
  email: bwvoss@gmail.com

# Build settings
markdown: kramdown
