# Site settings
email: ben@8thlight.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: benvoss
github_username:  bwvoss

# Build settings
markdown: kramdown
