# Site settings
email: ben@8thlight.com
description: # 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bwvoss.github.io" # the base hostname & protocol for your site
twitter_username: benvoss
github_username:  bwvoss

# Build settings
markdown: kramdown
